#!/bin/sh

# Getting the message:
# "Could not connect to Redis at 127.0.0.1:6379: Cannot assign requested address"
# ???
#
# https://github.com/antirez/redis/issues/340
#
# You have to tweak your network stack to reuse connections!
#
# echo 1 > /proc/sys/net/ipv4/tcp_tw_reuse
# sudo bash -c "echo 1 > /proc/sys/net/ipv4/tcp_tw_reuse"

echo
echo "Emptying gerty:*"
redis-cli KEYS "gerty:*" | xargs redis-cli DEL > /dev/null

# First create some duplicates.
echo "Creating duplicate records."
for a in `seq 1 1000`
	do
	redis-cli LPUSH gerty:job:queue {\"Transport\":\"apns\",\"Recipient\":\"hashhash\",\"Content\":\"Awesome!!!\"} > /dev/null
done

echo "Creating some valid, non-duplicate records."
for b in `seq 1 1000`
	do
	redis-cli LPUSH gerty:job:queue {\"Transport\":\"apns\",\"Recipient\":\"$b\",\"Content\":\"Awesome!!!\"} > /dev/null
done

echo "Creating invalid records."
for c in `seq 1 100`
	do
	redis-cli LPUSH gerty:job:queue {\"Transport\":\"invalid\"\"} > /dev/null
done

echo "Creating even more valid, non-duplicate records."
for d in `seq 10001 20000`
	do
	redis-cli LPUSH gerty:job:queue {\"Transport\":\"apns\",\"Recipient\":\"$d\",\"Content\":\"Awesome!!!\"} > /dev/null
done
